server:
   port: 8222
   context-path: /constellation

   ssl:
      key-store: classpath:1849945_xiaobao.pfx
      key-store-password: t2iPnliH
      keyStoreType: PKCS12
#http://localhost:8085/signin/hello
http:
 port: 8224
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dbusers
#    url: jdbc:mysql://127.0.0.1:3306/dbusers?useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/dbconstellation_produce?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456xiaoyou
     #  password: 123456
    sql-script-encoding: utf-8
