server:
   port: 8221
   context-path: /constellation
   ssl:
     key-store: classpath:constellation.keystore
     key-store-password: constellation
     keyStoreType: PKCS12
     keyAlias: constellation
#http://localhost:8085/signin/hello
http:
 port: 8223
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dbusers
#    url: jdbc:mysql://127.0.0.1:3306/dbusers?useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/dbconstellation_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456xiaoyou
    #password: 123456
    sql-script-encoding: utf-8
