server:
   port: 443
   context-path: /constellation
   ssl:
     key-store: classpath:214520819200829.pfx
     key-store-password: 214520819200829
     keyStoreType: PKCS12
     SSLEnabled: true
     secure: true
     SSLProtocol: TLSv1+TLSv1.1+TLSv1.2
     ciphers: TLS_RSA_WITH_AES_128_CBC_SHA,TLS_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_RSA_WITH_AES_256_CBC_SHA256"
#http://localhost:8085/signin/hello
http:
 port: 8223
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/dbusers
#    url: jdbc:mysql://127.0.0.1:3306/dbusers?useUnicode=true&amp;characterEncoding=utf-8
    url: jdbc:mysql://127.0.0.1:3306/dbconstellation_dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456xiaoyou
   # password: 123456
    sql-script-encoding: utf-8
